parameter1/pmmi-media-group-newsletters

tenants/all/templates/aw-continuous-processing.marko, tenants/all/templates/pw-contract-packaging.marko
Updated the header images for Continuous Processing and PW Contract Packaging. Additionally, updated the accent color for CP.
=> Updating header images & template colors

packages/common/components/blocks/standard/feature-content.marko, packages/common/components/blocks/standard/marko.json, packages/common/components/layouts/standard.marko
=> Rename feature block, fix image width & height

.idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/inspectionProfiles/profiles_settings.xml, .idea/modules.xml, .idea/pmmi-media-group-newsletters.iml, .idea/vcs.xml, .idea/workspace.xml, tenants/all/templates/aw-product-insights.marko, tenants/all/templates/aw-system-integrators.marko
Hi all,
I made changes to the newsletters per Bea's email.
=> Updates to Newsletters

tenants/all/templates/hcp-newsbrief.marko, tenants/all/templates/oem-shop-talk.marko
Added padding to shop-talk.marko and updated the current padding specs in Newsbrief.
=> Updating header spacing for HCP Newsbrief and OEM Shop Talk

packages/common/components/blocks/head.marko, packages/common/components/blocks/marko.json, packages/common/components/blocks/numeric/header.marko, packages/common/components/blocks/numeric/marko.json, packages/common/components/blocks/numeric/row-four.marko, packages/common/components/blocks/numeric/row-one.marko, packages/common/components/blocks/numeric/row-three.marko, packages/common/components/blocks/numeric/row-two.marko, packages/common/components/elements/marko.json, packages/common/components/elements/number.marko, packages/common/components/layouts/marko.json, packages/common/components/layouts/numeric.marko, packages/common/components/styles/marko.json, packages/common/components/styles/numeric.marko, tenants/all/config/core.js, tenants/all/templates/hcp-logistics-life-sciences.marko, tenants/all/templates/hcp-quick-hits.marko, tenants/all/templates/hcp-serialization-countdown.marko
=> Add numeric template

packages/common/components/blocks/ad/emailx.marko, packages/common/components/layouts/standard.marko, tenants/all/config/email-x.js
=> Add email-x position to standard layout

packages/common/components/blocks/ad/marko.json, packages/common/components/blocks/ad/nativex.marko, packages/common/components/blocks/standard/announcement.marko, packages/common/components/layouts/standard.marko, packages/common/components/marko.json
=> Add native-x support for top audience banner

packages/common/components/styles/standard.marko
=> Reset margin for paragraphs

packages/common/components/blocks/standard/content-list-item.marko, packages/common/components/blocks/standard/marko.json, packages/common/components/blocks/standard/product-list.marko, packages/common/components/layouts/standard.marko
=> Add product list component

tenants/all/templates/pw-contract-packaging.marko
=> Override the contract packaging logo

packages/common/components/blocks/standard/content-list-item.marko
=> Set height for content list item images

tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/oem-insights.marko, tenants/all/templates/oem-shop-talk.marko
=> Oem changes

packages/common/components/layouts/numeric.marko, tenants/all/config/email-x.js
=> Update bottom audience banner size

packages/common/components/blocks/ad/emailx.marko, packages/common/components/blocks/numeric/row-four.marko
=> Update bottom emailx banner stylings

packages/common/components/layouts/standard.marko, tenants/all/config/brands.js
=> Update titles to corresponding requests.

packages/common/components/blocks/ad/emailx.marko
=> Remove styling from bottom banner

packages/common/components/styles/standard.marko, tenants/all/templates/oem-insights.marko
=> Oem header styling adjusted and general styling change

packages/common/components/styles/standard.marko
=> Update margin on <p> tags

.idea/workspace.xml, packages/common/components/blocks/footer.marko
Updating standard newsletters to reflect footer address
=> Updating footer address to suite 1700

packages/common/components/blocks/standard/content-list-item.marko
This will allow for the workaround described in the attached card to work should it be decided to use it.
=> Verify existance of company before setting slug.

packages/common/components/layouts/numeric.marko
=> Add missing native-x audience banner

tenants/all/templates/aw-continuous-processing.marko, tenants/all/templates/pw-end-of-line-strategies.marko, tenants/all/templates/pw-machine-automation-insights.marko, tenants/all/templates/pw-new-issue-alert.marko, tenants/all/templates/pw-new-machinery.marko, tenants/all/templates/pw-packaging-insights.marko
Updating headers for PW and AW newsletters
=> Updating header images

tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/aw-process-automation.marko
I believe there is additional configuration options that will need to be added/transferred on the Newsletter Product for AW: Process Automation. (queryName, etc.)
=> Create/Transfer template and configuration. AW: Continuous Processing -> AW: Process Automation

packages/common/components/layouts/standard.marko
Adding syndicated content html comment section to standard.marko layout
=> Update standard.marko with HTML comment section

packages/common/components/blocks/footer-mundo.marko, tenants/mundo/config/i18n.js
=> Mundo footer styling adjustments & translation fixes

packages/common/components/blocks/footer-mundo.marko
=> Update footer language for mundo

tenants/mundo/config/brands.js
=> Capitalize Mundo in brands.js

packages/common/components/blocks/standard/product-list.marko
Allowing for dynamic coloring link of link text.
=> Update to product-list.marko

tenants/mundo/config/i18n.js
=> Add ‘watch’ translation to i18n.js file

packages/common/components/blocks/standard/announcement.marko
=> Scale banner image by campaign type.

packages/common/components/blocks/head.marko, packages/common/components/blocks/numeric/footer-new.marko, packages/common/components/blocks/numeric/header-new.marko, packages/common/components/blocks/numeric/marko.json, packages/common/components/blocks/numeric/row-five-new.marko, packages/common/components/blocks/numeric/row-four-new.marko, packages/common/components/blocks/numeric/row-one-new.marko, packages/common/components/blocks/numeric/row-three-new.marko, packages/common/components/blocks/numeric/row-two-new.marko, packages/common/components/elements/marko.json, packages/common/components/elements/number-new.marko, packages/common/components/layouts/marko.json, packages/common/components/layouts/numeric-new.marko, packages/common/components/styles/marko.json, packages/common/components/styles/numeric-new.marko, tenants/all/config/core.js, tenants/all/templates/hcp-quick-hits-new.marko
- Added new layout style, row components, header and footer style for this type of template
- I need help on adding a second dynamic accent color that can help control the background color of the numbers and the stroke color on top of the blocks according to the template.
=> Adding new Quick Hits Numeric Style tempalte

tenants/all/config/email-x.js, tenants/all/config/native-x.js
This should be the only one that needs to be updated as it has sizing passed in.
=> Email-X config updates HCP Quick Hits New

packages/common/components/blocks/ad/emailx.marko, packages/common/components/blocks/standard/announcement.marko, tenants/all/config/core.js, tenants/all/templates/hcp-logistics-for-the-life-sciences-new.marko, tenants/all/templates/hcp-serialization-countdown-new.marko
- created new versions of Serialization Countdown and Logistics for the Life Sciences.
- Updated show enticement and top announcement slots to include class "content-table".
=> Adding 2 new numeric template versions & adding classes to announcements

tenants/all/config/email-x.js, tenants/all/config/native-x.js
These were missed when the templates were created/merged.
=> Copy/Add ad x configs new numeric templates.

tenants/all/templates/aw-automation-skills.marko, tenants/all/templates/aw-factory-automation.marko, tenants/all/templates/aw-key-insights.marko
=> Updating header image instances

packages/common/components/blocks/ad/emailx.marko, packages/common/components/styles/numeric-new.marko, packages/common/components/styles/standard.marko
- Adding classes for buttons and text links to style head so that email code in both P1 and our native tool are more compatible.
- Also adding an image class to emailX image to optimize responsiveness.
=> Optimizing styling

packages/common/components/blocks/standard/announcement.marko, packages/common/components/styles/numeric-new.marko, packages/common/components/styles/standard.marko, tenants/all/templates/pw-contract-packaging.marko
- Adding new header image to PW-CP template
- Added class to nativeX so images don't break to second line on mobile views
- Added class styles to style docs
=> Updates to header image and nativeX styling

packages/common/components/blocks/standard/product-list.marko, packages/common/components/elements/content-action-link.marko, packages/common/components/styles/standard.marko, tenants/all/config/brands.js, tenants/all/templates/aw-automation-skills.marko, tenants/all/templates/aw-continuous-processing.marko, tenants/all/templates/aw-factory-automation.marko, tenants/all/templates/aw-food-bev-pharma.marko, tenants/all/templates/aw-key-insights.marko, tenants/all/templates/aw-news-insights.marko, tenants/all/templates/aw-process-automation.marko, tenants/all/templates/aw-product-insights.marko, tenants/all/templates/aw-system-integrators.marko, tenants/all/templates/oem-insights.marko, tenants/all/templates/pfw-joyces-voice.marko, tenants/all/templates/pw-contract-packaging.marko, tenants/all/templates/pw-editors-picks.marko, tenants/all/templates/pw-machine-automation-insights.marko, tenants/all/templates/pw-new-issue-alert.marko, tenants/all/templates/pw-packaging-insights.marko, tenants/all/templates/pw-shelf-impact.marko
- redefined header image & logo heights for rendering
- Optimized CTAs for consistent rendering, with fallbacks for Apple Mail, Gmail and outlook link behaviors.
=> Header and CTA updates

packages/common/components/blocks/footer.marko, packages/common/components/blocks/standard/announcement.marko, packages/common/components/blocks/standard/content-list-item.marko, packages/common/components/blocks/standard/content-list.marko, packages/common/components/blocks/standard/header.marko, packages/common/components/blocks/standard/product-list.marko, packages/common/components/blocks/standard/trending-list.marko, packages/common/components/styles/standard.marko
- Updated two column instances to optimize rendering for outlook.
=> Rendering Updates

tenants/all/config/native-x.js
=> Fix incorrect native-x slot id

tenants/all/templates/pw-shelf-impact.marko, tenants/mundo/templates/mundo-perspectivas.marko
=> Increase image size

packages/common/components/blocks/expo/body-wrapper.marko, packages/common/components/blocks/expo/content-list-item.marko, packages/common/components/blocks/expo/content-list.marko, packages/common/components/blocks/expo/curated.marko, packages/common/components/blocks/expo/exhibitor-search.marko, packages/common/components/blocks/expo/footer.marko, packages/common/components/blocks/expo/header.marko, packages/common/components/blocks/expo/main-video.marko, packages/common/components/blocks/expo/marko.json, packages/common/components/blocks/expo/schedule.marko, packages/common/components/blocks/expo/show-daily.marko, packages/common/components/blocks/expo/video-list-item.marko, packages/common/components/blocks/expo/video-list.marko, packages/common/components/blocks/head.marko, packages/common/components/blocks/marko.json, packages/common/components/layouts/expo.marko, packages/common/components/layouts/marko.json, packages/common/components/styles/expo.marko, packages/common/components/styles/marko.json, tenants/all/config/core.js, tenants/all/templates/pw-expo.marko
=> Create PW-Expo template

packages/common/components/blocks/expo/main-video.marko, packages/common/components/blocks/expo/video-list-item.marko
=> Add missing ; after &nbsp

packages/common/components/blocks/expo/header.marko, packages/common/components/blocks/expo/schedule-list-item.marko, packages/common/components/layouts/expo.marko, packages/common/components/styles/expo.marko
=> Add missing comments & adjust font color for 'Schedule' header

packages/common/components/layouts/expo.marko
=> Remove padding from bottom of schedule section and add tomorrow's date

packages/common/components/blocks/expo/body-wrapper.marko, packages/common/components/blocks/expo/content-list-item.marko, packages/common/components/blocks/expo/curated.marko, packages/common/components/blocks/expo/exhibitor-search.marko, packages/common/components/blocks/expo/footer.marko, packages/common/components/blocks/expo/header.marko, packages/common/components/blocks/expo/main-video.marko, packages/common/components/blocks/expo/schedule-list-item.marko, packages/common/components/blocks/expo/show-daily.marko, packages/common/components/blocks/expo/video-list-item.marko, packages/common/components/layouts/expo.marko
=> Fix comments so they aren’t stripped

packages/common/components/blocks/expo/schedule-list-item.marko
=> Remove padding between title and location

packages/common/components/blocks/footer-mundo.marko, tenants/mundo/config/brands.js
=> Update Mundo brandName, privacy url & Spanish version of 'Mexico City'

packages/common/components/blocks/2024-head.marko, packages/common/components/blocks/2024/ad/emailx.marko, packages/common/components/blocks/2024/ad/marko.json, packages/common/components/blocks/2024/ad/nativex.marko, packages/common/components/blocks/2024/article.marko, packages/common/components/blocks/2024/body-wrapper.marko, packages/common/components/blocks/2024/date-banner.marko, packages/common/components/blocks/2024/divider.marko, packages/common/components/blocks/2024/editors-note.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/2024/footer.marko, packages/common/components/blocks/2024/header.marko, packages/common/components/blocks/2024/marko.json, packages/common/components/blocks/2024/promo.marko, packages/common/components/blocks/2024/social.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/blocks/2024/what-we-are-reading.marko, packages/common/components/blocks/marko.json, packages/common/components/layouts/2024-weekly.marko, packages/common/components/layouts/marko.json, packages/common/graphql/fragments/website-content.js, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/pw-weekly.marko
=> Create 2024 weekly template and blocks

packages/common/components/blocks/2024/marko.json, packages/common/components/blocks/2024/stat.marko, packages/common/components/layouts/2024-daily.marko, packages/common/components/layouts/marko.json, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/pw-daily.marko
=> Create 2024 daily layout & include for Packaging World

packages/common/components/blocks/2024/article.marko, packages/common/components/blocks/2024/body-wrapper.marko, packages/common/components/blocks/2024/date-banner.marko, packages/common/components/blocks/2024/footer-mundo.marko, packages/common/components/blocks/2024/header.marko, packages/common/components/blocks/2024/marko.json, packages/common/components/blocks/2024/social-mundo.marko, packages/common/components/blocks/2024/social.marko, packages/common/components/layouts/2024-daily.marko, packages/common/components/layouts/2024-mundo.marko, packages/common/components/layouts/2024-weekly.marko, packages/common/components/layouts/marko.json, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/hcp-daily.marko, tenants/all/templates/oem-daily.marko, tenants/all/templates/pfw-daily.marko, tenants/mundo/config/core.js, tenants/mundo/config/email-x.js, tenants/mundo/config/native-x.js, tenants/mundo/templates/mundo-expo-pack.marko
=> Create remaining brand templates and make configurable

packages/common/components/blocks/cpgnext/announcement.marko, packages/common/components/blocks/cpgnext/marko.json, packages/common/components/blocks/cpgnext/nativex.marko, packages/common/components/layouts/cpgnext.marko, tenants/all/config/native-x.js
=> Add nativeX ad slot to CPGNext layout

packages/common/components/blocks/2024-head.marko, packages/common/components/blocks/2024/article.marko, packages/common/components/blocks/2024/date-banner.marko, packages/common/components/blocks/2024/promo.marko, packages/common/components/blocks/2024/stat.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/layouts/2024-mundo.marko
=> 2024 template styling adjustments

packages/common/components/blocks/2024/download.marko, packages/common/components/blocks/2024/marko.json, packages/common/components/layouts/2024-weekly.marko
=> Weekly revisions-Adjust 'download' nativeX placement block

packages/common/components/layouts/2024-daily.marko, packages/common/components/layouts/2024-weekly.marko
=> Add padding around Advertisement&Sponsor code PMMI adds manually

tenants/mundo/config/core.js
=> Update Social Media for Mundo

packages/common/components/layouts/2024-daily.marko
=> Remove extra line divider

tenants/mundo/config/core.js
=> Add youtube to Mundo’s footer

packages/common/components/blocks/2024/editors-note.marko, packages/common/components/layouts/2024-weekly.marko
=> Pass through alias in weekly template and add LinkedIn button image on Editor's note

packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/2024/webinar.marko, tenants/all/config/brands.js, tenants/all/config/core.js
=> Adjust URL Params for webinar and events blocks

packages/common/components/blocks/2024/editors-note.marko, packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/2024/stat.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/blocks/2024/what-we-are-reading.marko
=> Remove styling on the all header images

packages/common/components/blocks/cpgnext/event.marko
=> Adjust date format on CPGNext events

packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/cpgnext/event.marko
=> Include end date for events block

packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/cpgnext/event.marko
=> Change dash to en-dash on Events blocks

packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/webinar-mundo.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/blocks/cpgnext/event.marko
=> Use numeric format for all dates, only show Join Us header once CPGN.

packages/common/components/blocks/cpgnext/event.marko
=> Increase padding between events, account for padding difference around line divider

packages/common/components/blocks/numeric/footer.marko
=> Update footer styling for Quick Hits

packages/common/components/blocks/numeric/footer.marko
=> Update privacy policy url and adjust spacing after View Online

packages/common/components/blocks/2024-head.marko, packages/common/components/layouts/2024-daily.marko
=> Remove duplicate code in meta data

packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/2024/webinar-mundo.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/layouts/2024-daily.marko, packages/common/components/layouts/2024-mundo.marko, packages/common/components/layouts/2024-new-issue.marko, packages/common/components/layouts/2024-weekly.marko
=> Adjust Event and Webinar dates to match date of newsletter

packages/common/components/blocks/2024/date-banner-mundo.marko, packages/common/components/blocks/2024/date-banner.marko, packages/common/components/blocks/2024/editors-note.marko, packages/common/components/blocks/2024/header.marko, tenants/all/config/core.js, tenants/mundo/config/core.js
=> Double the image height or width to account for dpr=2 (blurriness)

.github/workflows/deploy-production.yml
Not sure where to find the 
ECR_REGISTRY:
IMG_PREFIX:
=> Move deployments to use ECR registry

tenants/mundo/config/native-x.js
Missed via: https://github.com/parameter1/pmmi-media-group-newsletters/pull/177
=> Use Mindful URI for Native-X delivery, Mundo

packages/common/components/blocks/2024/body-wrapper.marko, packages/common/components/blocks/2024/header.marko
=> Update Stealth link location

packages/common/components/blocks/numeric/header.marko, packages/common/components/blocks/numeric/row.marko, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/pmg-sustainable-packaging.marko
Shows Primary Color difference (quick hits 2024)
=> Create PMG Sustainable Packaging template

tenants/all/config/core.js
=> Updated PFW Editor Name, Social Links and Headshot for PFW Daily and PFW New Issue Alert

packages/common/components/blocks/2024/date-banner-mundo.marko, packages/common/components/blocks/2024/date-banner.marko, packages/common/components/blocks/2024/editors-note.marko, packages/common/components/blocks/2024/header.marko, packages/common/components/blocks/2024/promo.marko, packages/common/components/blocks/numeric/header.marko, packages/common/components/blocks/numeric/row.marko, packages/common/components/blocks/numeric/subscription.marko, packages/common/graphql/fragments/content-list.js
=> Increase Image quality to 100

packages/common/components/blocks/expo/content-list-item.marko, packages/common/components/blocks/expo/schedule-list-item.marko, packages/common/components/layouts/expo.marko
=> Pack Expo adjusments

packages/common/components/blocks/2024/date-banner-weekly.marko, packages/common/components/blocks/2024/date-banner.marko, packages/common/components/layouts/2024-new-issue.marko, packages/common/components/layouts/2024-weekly.marko
=> Update date banner for New Alert and PW-Weekly newsletters

tenants/mundo/config/email-x.js
=> Update EmailX id to use Mindful id-Mundo

packages/common/components/blocks/2024/webinar.marko
=> Ensure Upcoming webinars replace ?ref=web to ?ref=news

packages/common/components/blocks/automated/content.marko, packages/common/components/blocks/automated/footer.marko, packages/common/components/blocks/automated/head.marko, packages/common/components/blocks/automated/header.marko, packages/common/components/layouts/automated.marko, packages/common/graphql/fragments/content-list.js
I can't get the href=contentLink to actually link, it comes back as undefined.
File: `blocks > automated > content.marko`
=> Automated newsletter styling updates

packages/common/components/blocks/sustainable/content.marko, packages/common/components/blocks/sustainable/header.marko, packages/common/components/blocks/sustainable/promo.marko, packages/common/components/blocks/sustainable/webinar.marko, packages/common/graphql/fragments/website-content.js, packages/common/graphql/loader/multi-site-webinar-query.js, tenants/all/config/core.js
=> Sustainable changes

packages/common/components/blocks/sustainable/content.marko, packages/common/components/blocks/sustainable/header.marko, packages/common/components/blocks/sustainable/promo.marko, packages/common/components/blocks/sustainable/social.marko, packages/common/components/layouts/sustainable.marko, tenants/all/config/core.js
I have tried all of the solutions for removing the extra padding that Outlook Desktop adds to the template, but none of them work [https://www.emailonacid.com/blog/article/email-development/7-tips-and-tricks-regarding-margins-and-padding-in-html-emails/](url)
=> Add back padding styling

packages/common/components/layouts/sustainable.marko, tenants/all/config/core.js
=> Remove duplicate comments & remove weekly from title

packages/common/components/blocks/2024/article.marko, packages/common/components/blocks/2024/editors-note.marko, packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/2024/promo.marko, packages/common/components/blocks/2024/webinar-mundo.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/blocks/2024/what-we-are-reading.marko, packages/common/components/blocks/automated/most-popular.marko, packages/common/components/blocks/sustainable/webinar.marko
=> Add ! to ${content.name} to render HTML correctly

tenants/all/config/core.js, tenants/all/templates/pw-most-popular-soon-to-unengage.marko
=> Create a duplicate of the most popular newsletter

packages/common/loaders/multi-site-webinar-query.js
Adujist such that it prevent pushing the same webinar scheduled to multiple sites to the list multiple times.
=> Adjust upcoming multi site webinar block logic

packages/common/components/blocks/expo/body-wrapper-mundo.marko, packages/common/components/blocks/expo/curated-mundo.marko, packages/common/components/blocks/expo/exhibitor-search-mundo.marko, packages/common/components/blocks/expo/footer-mundo.marko, packages/common/components/blocks/expo/header-mundo.marko, packages/common/components/blocks/expo/header.marko, packages/common/components/blocks/expo/marko.json, packages/common/components/layouts/expo-mundo.marko, packages/common/components/layouts/expo.marko, packages/common/components/layouts/marko.json, tenants/mundo/config/core.js, tenants/mundo/config/i18n.js, tenants/mundo/templates/expo-live.marko
=> Create Mundo version of expo pack template
