parameter1/pmmi-media-group-newsletters

packages/common/components/blocks/standard/product-list.marko, tenants/all/config/brands.js, tenants/all/templates/hcp-newsbrief.marko
=> Update product image format, hcp logo & newsbrief image heights

tenants/all/templates/hcp-quick-hits.marko
This header will now be seen in “dark mode”
=> Update new header

packages/common/components/blocks/standard/announcement.marko
=> Adjust image styles for announcement block

packages/common/components/blocks/standard/header.marko, tenants/all/templates/aw-process-automation.marko, tenants/mundo/config/core.js, tenants/mundo/templates/mundo-perspectivas.marko
The background colors were not being set correctly due to a breaking change here: https://github.com/jwade1327/pmmi-media-group-newsletters/commit/1ebfc22378e2e996869b45dc1356680daf7b7771 that was looking for secondaryBackgroundColor to be set on all newsletter configurations which it currently is not. 
EDITED: The change in this PR will use the previously used behavior of passing the secondaryBackground color as an input to the header (Mundo's configuration has been updated accordingly) and additionally adding an input parameter for taglineTextColor which will allow the alteration of the tagline text color.
=> Correct tagline background and text colors.

tenants/all/config/native-x.js
This will now allow all native-x ads to display properly
=> Fix indentation for native-x ad slots for hcp-newsbrief-updated

tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/templates/pfw-hand-picked.marko, tenants/all/templates/pfw-new-issue-alert.marko
Added two new templates: PFW New Issue Alert and PFW Hand Picked.
Update to PW:Contract Packaging Template. Switched out the logo and header image and updated the name and tagline.
Note, this was the first time I've created a new template (even though it was just a clone). I did add the newsletter instance in the [manage.pmmimediagroup.com/emails](https://manage.pmmimediagroup.com/emails/) backend. I also figured that I needed to update the email instance and tagline in the core.js file, so please let me know if this is not correct. 
Also, I think something needs to get hooked up with EmailX, as I have the attached error on both new templates: https://share.getcloudapp.com/wbuzrjl8
=> Created 2 new templates; Updated 1 existing template

tenants/all/templates/pfw-hand-picked.marko, tenants/all/templates/pfw-new-issue-alert.marko
This should (hopefully) prevent the distortion described/shown previously by these header images.
Previously:
Now:
=> Correct new template header image sizing.

packages/common/components/blocks/standard/announcement.marko
Change is super subtle here:
BEFORE:
AFTER:
=> Adjust image alignment based on campaign type.

packages/common/components/layouts/numeric-new.marko
=> Change numeric footer over to the new numeric footer.

packages/common/components/blocks/numeric/row-five-new.marko, packages/common/components/blocks/numeric/row-four-new.marko, packages/common/components/blocks/numeric/row-one-new.marko, packages/common/components/blocks/numeric/row-three-new.marko, packages/common/components/blocks/numeric/row-two-new.marko
I goofed here https://github.com/parameter1/pmmi-media-group-newsletters/pull/73/commits/68d67f4faf6face5219c4a2a304bb3db82a69263 thinking this was suppose to be reducing the content rows to the placeholder ad section but it was suppose to be increasing the placeholder ad section to the width of the content rows.
=> Set row widths back to 100% New Numeric Template

packages/common/components/blocks/numeric/row-five-new.marko, packages/common/components/blocks/numeric/row-four-new.marko, packages/common/components/blocks/numeric/row-one-new.marko, packages/common/components/blocks/numeric/row-three-new.marko, packages/common/components/blocks/numeric/row-two-new.marko
=> Adjust row “inner-width” to 592px over 552px. New Numeric Template.

tenants/all/templates/hcp-quick-hits-new.marko, tenants/all/templates/pw-contract-packaging.marko
• Replaced Quick Hits image with dark mode compatible header image
• removed Natalie image link to CM+P newsletter (this should be re-filled in the near future).
=> Updating headers

tenants/all/templates/pw-shelf-impact.marko, tenants/mundo/templates/mundo-perspectivas.marko
Current:
2 newsletters being changed:
=> Adjust styling to prevent image from getting too narrow

packages/common/components/blocks/standard/announcement.marko
=> Add credspark to url match in announcement block

packages/common/components/blocks/cpgnext/social.marko, packages/common/components/blocks/cpgnext/what-we-are-reading.marko, packages/common/components/layouts/cpgnext.marko
Header now stays center:
Add padding above socials:
What we're reading section now has padding:
=> Cpg revisions

packages/common/components/blocks/cpgnext/article.marko, packages/common/components/layouts/cpgnext.marko
DEV: (no teaser)
PROD: (with teaser)
DEV & PROD: (with teaser)
=> Make withTeaser optional for article block-CPG Next

packages/common/components/blocks/cpgnext/announcement.marko, packages/common/components/layouts/cpgnext.marko
=> Move Top announcement ad to top of cpgnext layout

packages/common/components/blocks/cpgnext/editorial-intro.marko, packages/common/components/blocks/cpgnext/event.marko, packages/common/components/layouts/cpgnext.marko
Remove padding-top:
Pulls in Events scheduled to CPGNext:
=> Add 'Events' block to CPGnext layout, configure and adjust styling

packages/common/components/blocks/2024/ad/nativex.marko, packages/common/components/blocks/2024/article.marko, packages/common/components/blocks/2024/body-wrapper.marko, packages/common/components/blocks/2024/divider.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/2024/footer-mundo.marko, packages/common/components/blocks/2024/footer.marko, packages/common/components/blocks/2024/header-mundo.marko, packages/common/components/blocks/2024/marko.json, packages/common/components/blocks/2024/promo.marko, packages/common/components/blocks/2024/stat.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/layouts/2024-mundo.marko, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/cmp-daily.marko, tenants/mundo/config/core.js, tenants/mundo/templates/mundo-expo-pack.marko
=> Spacing adjustments, pass through primary color on native ads, update footers 2024 templates

packages/common/components/blocks/2024-head.marko, packages/common/components/blocks/2024/editors-note.marko, packages/common/components/blocks/2024/promo.marko
=> Adjust padding ‘editor’s note’ and promo block

packages/common/components/blocks/2024/events-mundo.marko, packages/common/components/blocks/2024/events.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/layouts/2024-daily.marko, packages/common/components/layouts/2024-mundo.marko
=> Add Url params on Event and Webinar blocks

tenants/mundo/config/core.js
This passes through url params for events and webinars:
=> Add brandShort for mundo expo pack

packages/common/components/blocks/cpgnext/event.marko, packages/common/components/layouts/cpgnext.marko, tenants/all/config/core.js
=> Add url params to Events block on CPGNext layout

packages/common/components/blocks/2024/marko.json, packages/common/components/blocks/2024/webinar-mundo.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/layouts/2024-mundo.marko, packages/common/graphql/fragments/website-content.js
=> Create Mundo Webinar block to account for Spanish date format

packages/common/components/blocks/2024/events.marko
Missed here: https://github.com/parameter1/pmmi-media-group-newsletters/pull/152/files#diff-eac3d3be26d9a252e1e0d6655594b5123d37257d28657babdc1f76fa5bbb15b2R46
=> Use numeric for end date format on events

packages/common/components/blocks/cpgnext/event.marko
=> Add padding between events-CPGNext layout

packages/common/components/blocks/2024/article.marko, packages/common/components/blocks/expo/content-list-item.marko, packages/common/components/blocks/expo/main-video.marko, packages/common/components/blocks/expo/video-list-item.marko, packages/common/components/blocks/numeric/row-five-new.marko, packages/common/components/blocks/numeric/row-four-new.marko, packages/common/components/blocks/numeric/row-four.marko, packages/common/components/blocks/numeric/row-one-new.marko, packages/common/components/blocks/numeric/row-one.marko, packages/common/components/blocks/numeric/row-three-new.marko, packages/common/components/blocks/numeric/row-three.marko, packages/common/components/blocks/numeric/row-two-new.marko, packages/common/components/blocks/numeric/row-two.marko, packages/common/components/blocks/standard/content-list-item.marko, packages/common/components/blocks/standard/feature-content.marko, packages/common/components/blocks/standard/product-list.marko, packages/common/components/blocks/standard/sponsor.marko, packages/common/components/blocks/standard/trending-list.marko, packages/common/graphql/fragments/content-list.js
=> Render ProSource content with appropriate link and "eyebrow"

packages/common/components/layouts/2024-mundo.marko, packages/common/components/layouts/2024-new-issue.marko, packages/common/components/layouts/2024-weekly.marko
=> Remove title from newsletter-root in weekly, new-alert, & mundo layouts

.github/workflows/deploy-production.yml
Missed in: https://github.com/parameter1/pmmi-media-group-newsletters/pull/173
=> Add tenant matrix to build-newsletters workflow

docker-compose.yml, tenants/mundo/config/email-x.js
This was additionally missed in https://github.com/parameter1/pmmi-media-group-newsletters/pull/177 and subsequently via https://github.com/parameter1/pmmi-media-group-newsletters/pull/179
=> Correct Email-X API URI for Mundo

packages/common/components/blocks/numeric/row.marko
=> Copy over image styling from ‘old’ numeric template

tenants/all/config/core.js
=> Change name of CMP editor’s image

packages/common/components/blocks/2024/header.marko, packages/common/components/blocks/numeric/header.marko
=> Set image options to double the attrs size

packages/common/components/blocks/expo/schedule-list-item.marko, packages/common/components/layouts/expo.marko
=> Update 'Up Next' section in Pack Expo

packages/common/components/blocks/2024-head.marko, packages/common/components/blocks/2024/date-banner.marko
=> Ensure  correct 'view online' font-size on mobile

packages/common/components/blocks/2024/webinar-mundo.marko, packages/common/components/blocks/2024/webinar.marko, packages/common/components/blocks/sustainable/webinar.marko
Ajust the logic on the webinars block to allow for back fill of the Webinars block.  Meaning it will attempt to populate it with 2 upcoming and then back fill the 3 item display limit with archived webinars.
https://trello.com/c/kcRWtfvy/1069-update-logic-for-webinar-section-of-newsletters
Mundo:
=> Adjust the webinars block to back fill only when there are not 3 upcoming webinars

packages/common/components/blocks/expo/content-list-item.marko, packages/common/components/blocks/expo/curated-mundo.marko, packages/common/components/blocks/expo/curated.marko, packages/common/components/blocks/expo/exhibitor-search-mundo.marko, packages/common/components/blocks/expo/exhibitor-search.marko, packages/common/components/blocks/expo/footer-mundo.marko, packages/common/components/blocks/expo/footer.marko, packages/common/components/blocks/expo/header-mundo.marko, packages/common/components/blocks/expo/header.marko, packages/common/components/blocks/expo/marko.json, packages/common/components/blocks/expo/schedule-list-item-mundo.marko, packages/common/components/blocks/expo/schedule-list-mundo.marko, packages/common/components/blocks/expo/show-daily.marko, packages/common/components/layouts/expo-mundo.marko, packages/common/components/layouts/expo.marko
=> Pack Expo revisions (img styling & padding adjustments)

packages/common/components/layouts/expo-mundo.marko
Newsletter date 9/30 'Up Next' section displays 10/1
=> Adjust displayDate to display tomorrow’s date
